import type { NextPage } from 'next';
import Head from 'next/head';
import { Home } from '../components/Home';
import styles from '../styles/home-page.module.css';

const HomePage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Barcode Cam</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Home />
    </div>
  );
};

export default HomePage;
